-- =============================================================
-- Lug'atcha — boshlang'ich so'zlar (106 ta)
-- 0001_init.sql dan KEYIN ishga tushiring.
-- Qayta ishga tushirsangiz, avval shu so'zlarni o'chirib, qaytadan qo'shadi.
-- =============================================================

delete from public.words
where english in ('cat', 'dog', 'cow', 'horse', 'sheep', 'lion', 'tiger', 'elephant', 'monkey', 'bear', 'rabbit', 'fish', 'bird', 'chicken', 'duck', 'frog', 'bee', 'snake', 'fox', 'wolf', 'apple', 'banana', 'orange', 'grape', 'strawberry', 'watermelon', 'lemon', 'peach', 'cherry', 'pear', 'pineapple', 'melon', 'apricot', 'pomegranate', 'fig', 'red', 'blue', 'green', 'yellow', 'orange', 'purple', 'pink', 'black', 'white', 'brown', 'gray', 'gold', 'book', 'pen', 'pencil', 'teacher', 'student', 'school', 'desk', 'bag', 'ruler', 'notebook', 'paper', 'eraser', 'board', 'lesson', 'homework', 'mother', 'father', 'brother', 'sister', 'grandmother', 'grandfather', 'baby', 'family', 'son', 'daughter', 'uncle', 'aunt', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'zero', 'hundred', 'sun', 'moon', 'star', 'water', 'tree', 'flower', 'house', 'car', 'ball', 'bread', 'milk', 'egg', 'happy', 'sad', 'big', 'small', 'hot', 'cold', 'hello', 'thank you');

insert into public.words (english, uzbek, transcription, example_en, example_uz, category, emoji) values
  ('cat', 'mushuk', '[kæt]', 'The cat is sleeping.', 'Mushuk uxlayapti.', 'hayvonlar', '🐱'),
  ('dog', 'it', '[dɒɡ]', 'My dog is friendly.', 'Mening itim do''stona.', 'hayvonlar', '🐶'),
  ('cow', 'sigir', '[kaʊ]', 'The cow gives milk.', 'Sigir sut beradi.', 'hayvonlar', '🐮'),
  ('horse', 'ot', '[hɔːs]', 'The horse runs fast.', 'Ot tez yuguradi.', 'hayvonlar', '🐴'),
  ('sheep', 'qo''y', '[ʃiːp]', 'The sheep has soft wool.', 'Qo''yning yumshoq juni bor.', 'hayvonlar', '🐑'),
  ('lion', 'sher', '[ˈlaɪ.ən]', 'The lion is the king.', 'Sher — podsho.', 'hayvonlar', '🦁'),
  ('tiger', 'yo''lbars', '[ˈtaɪ.ɡər]', 'The tiger has stripes.', 'Yo''lbarsning chiziqlari bor.', 'hayvonlar', '🐯'),
  ('elephant', 'fil', '[ˈel.ɪ.fənt]', 'The elephant is very big.', 'Fil juda katta.', 'hayvonlar', '🐘'),
  ('monkey', 'maymun', '[ˈmʌŋ.ki]', 'The monkey loves bananas.', 'Maymun bananni yaxshi ko''radi.', 'hayvonlar', '🐵'),
  ('bear', 'ayiq', '[beər]', 'The bear sleeps in winter.', 'Ayiq qishda uxlaydi.', 'hayvonlar', '🐻'),
  ('rabbit', 'quyon', '[ˈræb.ɪt]', 'The rabbit eats carrots.', 'Quyon sabzi yeydi.', 'hayvonlar', '🐰'),
  ('fish', 'baliq', '[fɪʃ]', 'The fish swims in water.', 'Baliq suvda suzadi.', 'hayvonlar', '🐟'),
  ('bird', 'qush', '[bɜːd]', 'The bird can fly.', 'Qush ucha oladi.', 'hayvonlar', '🐦'),
  ('chicken', 'tovuq', '[ˈtʃɪk.ɪn]', 'The chicken lays eggs.', 'Tovuq tuxum qiladi.', 'hayvonlar', '🐔'),
  ('duck', 'o''rdak', '[dʌk]', 'The duck is in the pond.', 'O''rdak hovuzda.', 'hayvonlar', '🦆'),
  ('frog', 'qurbaqa', '[frɒɡ]', 'The frog jumps high.', 'Qurbaqa baland sakraydi.', 'hayvonlar', '🐸'),
  ('bee', 'asalari', '[biː]', 'The bee makes honey.', 'Asalari asal qiladi.', 'hayvonlar', '🐝'),
  ('snake', 'ilon', '[sneɪk]', 'The snake is long.', 'Ilon uzun.', 'hayvonlar', '🐍'),
  ('fox', 'tulki', '[fɒks]', 'The fox is clever.', 'Tulki ayyor.', 'hayvonlar', '🦊'),
  ('wolf', 'bo''ri', '[wʊlf]', 'The wolf lives in the forest.', 'Bo''ri o''rmonda yashaydi.', 'hayvonlar', '🐺'),
  ('apple', 'olma', '[ˈæp.əl]', 'I eat a red apple.', 'Men qizil olma yeyman.', 'mevalar', '🍎'),
  ('banana', 'banan', '[bəˈnɑː.nə]', 'The banana is yellow.', 'Banan sariq.', 'mevalar', '🍌'),
  ('orange', 'apelsin', '[ˈɒr.ɪndʒ]', 'The orange is sweet.', 'Apelsin shirin.', 'mevalar', '🍊'),
  ('grape', 'uzum', '[ɡreɪp]', 'Grapes grow on a vine.', 'Uzum tokda o''sadi.', 'mevalar', '🍇'),
  ('strawberry', 'qulupnay', '[ˈstrɔː.bər.i]', 'I love strawberry.', 'Men qulupnayni yaxshi ko''raman.', 'mevalar', '🍓'),
  ('watermelon', 'tarvuz', '[ˈwɔː.təˌmel.ən]', 'Watermelon is juicy.', 'Tarvuz sersuv.', 'mevalar', '🍉'),
  ('lemon', 'limon', '[ˈlem.ən]', 'The lemon is sour.', 'Limon nordon.', 'mevalar', '🍋'),
  ('peach', 'shaftoli', '[piːtʃ]', 'The peach is soft.', 'Shaftoli yumshoq.', 'mevalar', '🍑'),
  ('cherry', 'gilos', '[ˈtʃer.i]', 'Cherries are small and red.', 'Gilos kichik va qizil.', 'mevalar', '🍒'),
  ('pear', 'nok', '[peər]', 'The pear is green.', 'Nok yashil.', 'mevalar', '🍐'),
  ('pineapple', 'ananas', '[ˈpaɪnˌæp.əl]', 'Pineapple is tropical.', 'Ananas tropik meva.', 'mevalar', '🍍'),
  ('melon', 'qovun', '[ˈmel.ən]', 'The melon smells sweet.', 'Qovun shirin hidlaydi.', 'mevalar', '🍈'),
  ('apricot', 'o''rik', '[ˈeɪ.prɪ.kɒt]', 'Apricots are orange.', 'O''rik to''q sariq.', 'mevalar', '🍑'),
  ('pomegranate', 'anor', '[ˈpɒm.ɪˌɡræn.ɪt]', 'The pomegranate has many seeds.', 'Anorning ko''p donalari bor.', 'mevalar', '🔴'),
  ('fig', 'anjir', '[fɪɡ]', 'The fig is very sweet.', 'Anjir juda shirin.', 'mevalar', '🟣'),
  ('red', 'qizil', '[red]', 'The apple is red.', 'Olma qizil.', 'ranglar', '🔴'),
  ('blue', 'ko''k', '[bluː]', 'The sky is blue.', 'Osmon ko''k.', 'ranglar', '🔵'),
  ('green', 'yashil', '[ɡriːn]', 'The grass is green.', 'O''t yashil.', 'ranglar', '🟢'),
  ('yellow', 'sariq', '[ˈjel.əʊ]', 'The sun is yellow.', 'Quyosh sariq.', 'ranglar', '🟡'),
  ('orange', 'to''q sariq', '[ˈɒr.ɪndʒ]', 'I have an orange ball.', 'Menda to''q sariq to''p bor.', 'ranglar', '🟠'),
  ('purple', 'binafsha', '[ˈpɜː.pəl]', 'The flower is purple.', 'Gul binafsha rangda.', 'ranglar', '🟣'),
  ('pink', 'pushti', '[pɪŋk]', 'She likes pink.', 'U pushti rangni yoqtiradi.', 'ranglar', '🌸'),
  ('black', 'qora', '[blæk]', 'The cat is black.', 'Mushuk qora.', 'ranglar', '⚫'),
  ('white', 'oq', '[waɪt]', 'The snow is white.', 'Qor oq.', 'ranglar', '⚪'),
  ('brown', 'jigarrang', '[braʊn]', 'The bear is brown.', 'Ayiq jigarrang.', 'ranglar', '🟤'),
  ('gray', 'kulrang', '[ɡreɪ]', 'The elephant is gray.', 'Fil kulrang.', 'ranglar', '🩶'),
  ('gold', 'oltin rang', '[ɡəʊld]', 'The star is gold.', 'Yulduz oltin rangda.', 'ranglar', '🌟'),
  ('book', 'kitob', '[bʊk]', 'I read a book.', 'Men kitob o''qiyman.', 'maktab', '📖'),
  ('pen', 'ruchka', '[pen]', 'I write with a pen.', 'Men ruchka bilan yozaman.', 'maktab', '🖊️'),
  ('pencil', 'qalam', '[ˈpen.səl]', 'The pencil is sharp.', 'Qalam o''tkir.', 'maktab', '✏️'),
  ('teacher', 'o''qituvchi', '[ˈtiː.tʃər]', 'The teacher is kind.', 'O''qituvchi mehribon.', 'maktab', '👩‍🏫'),
  ('student', 'o''quvchi', '[ˈstjuː.dənt]', 'The student is smart.', 'O''quvchi aqlli.', 'maktab', '🧑‍🎓'),
  ('school', 'maktab', '[skuːl]', 'I go to school.', 'Men maktabga boraman.', 'maktab', '🏫'),
  ('desk', 'parta', '[desk]', 'My books are on the desk.', 'Kitoblarim partada.', 'maktab', '🪑'),
  ('bag', 'sumka', '[bæɡ]', 'My bag is heavy.', 'Sumkam og''ir.', 'maktab', '🎒'),
  ('ruler', 'chizg''ich', '[ˈruː.lər]', 'I draw a line with a ruler.', 'Chizg''ich bilan chiziq chizaman.', 'maktab', '📏'),
  ('notebook', 'daftar', '[ˈnəʊt.bʊk]', 'I write in my notebook.', 'Men daftarimga yozaman.', 'maktab', '📓'),
  ('paper', 'qog''oz', '[ˈpeɪ.pər]', 'I draw on paper.', 'Men qog''ozga rasm chizaman.', 'maktab', '📄'),
  ('eraser', 'o''chirg''ich', '[ɪˈreɪ.zər]', 'I use an eraser.', 'Men o''chirg''ichdan foydalanaman.', 'maktab', '🧼'),
  ('board', 'doska', '[bɔːd]', 'The teacher writes on the board.', 'O''qituvchi doskaga yozadi.', 'maktab', '📋'),
  ('lesson', 'dars', '[ˈles.ən]', 'The lesson is interesting.', 'Dars qiziqarli.', 'maktab', '📚'),
  ('homework', 'uy vazifasi', '[ˈhəʊm.wɜːk]', 'I do my homework.', 'Men uy vazifamni bajaraman.', 'maktab', '📝'),
  ('mother', 'ona', '[ˈmʌð.ər]', 'I love my mother.', 'Men onamni yaxshi ko''raman.', 'oila', '👩'),
  ('father', 'ota', '[ˈfɑː.ðər]', 'My father is tall.', 'Otam baland bo''yli.', 'oila', '👨'),
  ('brother', 'aka / uka', '[ˈbrʌð.ər]', 'My brother is funny.', 'Akam kulgili.', 'oila', '👦'),
  ('sister', 'opa / singil', '[ˈsɪs.tər]', 'My sister is little.', 'Singlim kichkina.', 'oila', '👧'),
  ('grandmother', 'buvi', '[ˈɡrænˌmʌð.ər]', 'My grandmother tells stories.', 'Buvim ertak aytadi.', 'oila', '👵'),
  ('grandfather', 'bobo', '[ˈɡrænˌfɑː.ðər]', 'My grandfather is wise.', 'Bobom dono.', 'oila', '👴'),
  ('baby', 'chaqaloq', '[ˈbeɪ.bi]', 'The baby is sleeping.', 'Chaqaloq uxlayapti.', 'oila', '👶'),
  ('family', 'oila', '[ˈfæm.əl.i]', 'I love my family.', 'Men oilamni yaxshi ko''raman.', 'oila', '👨‍👩‍👧‍👦'),
  ('son', 'o''g''il', '[sʌn]', 'He is my son.', 'U mening o''g''lim.', 'oila', '👦'),
  ('daughter', 'qiz', '[ˈdɔː.tər]', 'She is my daughter.', 'U mening qizim.', 'oila', '👧'),
  ('uncle', 'amaki / tog''a', '[ˈʌŋ.kəl]', 'My uncle is funny.', 'Amakim kulgili.', 'oila', '🧔'),
  ('aunt', 'amma / xola', '[ɑːnt]', 'My aunt is kind.', 'Xolam mehribon.', 'oila', '👩'),
  ('one', 'bir', '[wʌn]', 'I have one apple.', 'Menda bitta olma bor.', 'raqamlar', '1️⃣'),
  ('two', 'ikki', '[tuː]', 'I see two cats.', 'Men ikkita mushuk ko''raman.', 'raqamlar', '2️⃣'),
  ('three', 'uch', '[θriː]', 'There are three birds.', 'Uchta qush bor.', 'raqamlar', '3️⃣'),
  ('four', 'to''rt', '[fɔː]', 'A dog has four legs.', 'Itning to''rtta oyog''i bor.', 'raqamlar', '4️⃣'),
  ('five', 'besh', '[faɪv]', 'I have five fingers.', 'Mening beshta barmog''im bor.', 'raqamlar', '5️⃣'),
  ('six', 'olti', '[sɪks]', 'Six eggs are in the box.', 'Qutida oltita tuxum bor.', 'raqamlar', '6️⃣'),
  ('seven', 'yetti', '[ˈsev.ən]', 'A week has seven days.', 'Haftada yetti kun bor.', 'raqamlar', '7️⃣'),
  ('eight', 'sakkiz', '[eɪt]', 'A spider has eight legs.', 'O''rgimchakning sakkizta oyog''i bor.', 'raqamlar', '8️⃣'),
  ('nine', 'to''qqiz', '[naɪn]', 'I am nine years old.', 'Men to''qqiz yoshdaman.', 'raqamlar', '9️⃣'),
  ('ten', 'o''n', '[ten]', 'I can count to ten.', 'Men o''ngacha sanay olaman.', 'raqamlar', '🔟'),
  ('zero', 'nol', '[ˈzɪə.rəʊ]', 'Zero comes before one.', 'Nol birdan oldin keladi.', 'raqamlar', '0️⃣'),
  ('hundred', 'yuz', '[ˈhʌn.drəd]', 'One hundred is a big number.', 'Yuz — katta son.', 'raqamlar', '💯'),
  ('sun', 'quyosh', '[sʌn]', 'The sun is bright.', 'Quyosh yorqin.', 'umumiy', '☀️'),
  ('moon', 'oy', '[muːn]', 'The moon is in the sky.', 'Oy osmonda.', 'umumiy', '🌙'),
  ('star', 'yulduz', '[stɑː]', 'I see a star.', 'Men yulduz ko''raman.', 'umumiy', '⭐'),
  ('water', 'suv', '[ˈwɔː.tər]', 'I drink water.', 'Men suv ichaman.', 'umumiy', '💧'),
  ('tree', 'daraxt', '[triː]', 'The tree is tall.', 'Daraxt baland.', 'umumiy', '🌳'),
  ('flower', 'gul', '[ˈflaʊ.ər]', 'The flower smells nice.', 'Gul yoqimli hidlaydi.', 'umumiy', '🌷'),
  ('house', 'uy', '[haʊs]', 'My house is warm.', 'Mening uyim issiq.', 'umumiy', '🏠'),
  ('car', 'mashina', '[kɑː]', 'The car is fast.', 'Mashina tez.', 'umumiy', '🚗'),
  ('ball', 'to''p', '[bɔːl]', 'I play with a ball.', 'Men to''p bilan o''ynayman.', 'umumiy', '⚽'),
  ('bread', 'non', '[bred]', 'I eat bread.', 'Men non yeyman.', 'umumiy', '🍞'),
  ('milk', 'sut', '[mɪlk]', 'I drink milk.', 'Men sut ichaman.', 'umumiy', '🥛'),
  ('egg', 'tuxum', '[eɡ]', 'The egg is white.', 'Tuxum oq.', 'umumiy', '🥚'),
  ('happy', 'xursand', '[ˈhæp.i]', 'I am happy today.', 'Men bugun xursandman.', 'umumiy', '😄'),
  ('sad', 'xafa', '[sæd]', 'Do not be sad.', 'Xafa bo''lma.', 'umumiy', '😢'),
  ('big', 'katta', '[bɪɡ]', 'The elephant is big.', 'Fil katta.', 'umumiy', '🐘'),
  ('small', 'kichik', '[smɔːl]', 'The ant is small.', 'Chumoli kichik.', 'umumiy', '🐜'),
  ('hot', 'issiq', '[hɒt]', 'The tea is hot.', 'Choy issiq.', 'umumiy', '🔥'),
  ('cold', 'sovuq', '[kəʊld]', 'The ice is cold.', 'Muz sovuq.', 'umumiy', '❄️'),
  ('hello', 'salom', '[heˈləʊ]', 'Hello, my friend!', 'Salom, do''stim!', 'umumiy', '👋'),
  ('thank you', 'rahmat', '[θæŋk juː]', 'Thank you very much.', 'Katta rahmat.', 'umumiy', '🙏');
