// 100 ta boshlang'ich so'z — bolalar uchun.
// Bu fayl seed skripti va seed.sql generatori tomonidan ishlatiladi.

export const words = [
  // ----------------------- HAYVONLAR (animals) -----------------------
  { english: "cat", uzbek: "mushuk", transcription: "[kæt]", example_en: "The cat is sleeping.", example_uz: "Mushuk uxlayapti.", category: "hayvonlar", emoji: "🐱" },
  { english: "dog", uzbek: "it", transcription: "[dɒɡ]", example_en: "My dog is friendly.", example_uz: "Mening itim do'stona.", category: "hayvonlar", emoji: "🐶" },
  { english: "cow", uzbek: "sigir", transcription: "[kaʊ]", example_en: "The cow gives milk.", example_uz: "Sigir sut beradi.", category: "hayvonlar", emoji: "🐮" },
  { english: "horse", uzbek: "ot", transcription: "[hɔːs]", example_en: "The horse runs fast.", example_uz: "Ot tez yuguradi.", category: "hayvonlar", emoji: "🐴" },
  { english: "sheep", uzbek: "qo'y", transcription: "[ʃiːp]", example_en: "The sheep has soft wool.", example_uz: "Qo'yning yumshoq juni bor.", category: "hayvonlar", emoji: "🐑" },
  { english: "lion", uzbek: "sher", transcription: "[ˈlaɪ.ən]", example_en: "The lion is the king.", example_uz: "Sher — podsho.", category: "hayvonlar", emoji: "🦁" },
  { english: "tiger", uzbek: "yo'lbars", transcription: "[ˈtaɪ.ɡər]", example_en: "The tiger has stripes.", example_uz: "Yo'lbarsning chiziqlari bor.", category: "hayvonlar", emoji: "🐯" },
  { english: "elephant", uzbek: "fil", transcription: "[ˈel.ɪ.fənt]", example_en: "The elephant is very big.", example_uz: "Fil juda katta.", category: "hayvonlar", emoji: "🐘" },
  { english: "monkey", uzbek: "maymun", transcription: "[ˈmʌŋ.ki]", example_en: "The monkey loves bananas.", example_uz: "Maymun bananni yaxshi ko'radi.", category: "hayvonlar", emoji: "🐵" },
  { english: "bear", uzbek: "ayiq", transcription: "[beər]", example_en: "The bear sleeps in winter.", example_uz: "Ayiq qishda uxlaydi.", category: "hayvonlar", emoji: "🐻" },
  { english: "rabbit", uzbek: "quyon", transcription: "[ˈræb.ɪt]", example_en: "The rabbit eats carrots.", example_uz: "Quyon sabzi yeydi.", category: "hayvonlar", emoji: "🐰" },
  { english: "fish", uzbek: "baliq", transcription: "[fɪʃ]", example_en: "The fish swims in water.", example_uz: "Baliq suvda suzadi.", category: "hayvonlar", emoji: "🐟" },
  { english: "bird", uzbek: "qush", transcription: "[bɜːd]", example_en: "The bird can fly.", example_uz: "Qush ucha oladi.", category: "hayvonlar", emoji: "🐦" },
  { english: "chicken", uzbek: "tovuq", transcription: "[ˈtʃɪk.ɪn]", example_en: "The chicken lays eggs.", example_uz: "Tovuq tuxum qiladi.", category: "hayvonlar", emoji: "🐔" },
  { english: "duck", uzbek: "o'rdak", transcription: "[dʌk]", example_en: "The duck is in the pond.", example_uz: "O'rdak hovuzda.", category: "hayvonlar", emoji: "🦆" },
  { english: "frog", uzbek: "qurbaqa", transcription: "[frɒɡ]", example_en: "The frog jumps high.", example_uz: "Qurbaqa baland sakraydi.", category: "hayvonlar", emoji: "🐸" },
  { english: "bee", uzbek: "asalari", transcription: "[biː]", example_en: "The bee makes honey.", example_uz: "Asalari asal qiladi.", category: "hayvonlar", emoji: "🐝" },
  { english: "snake", uzbek: "ilon", transcription: "[sneɪk]", example_en: "The snake is long.", example_uz: "Ilon uzun.", category: "hayvonlar", emoji: "🐍" },
  { english: "fox", uzbek: "tulki", transcription: "[fɒks]", example_en: "The fox is clever.", example_uz: "Tulki ayyor.", category: "hayvonlar", emoji: "🦊" },
  { english: "wolf", uzbek: "bo'ri", transcription: "[wʊlf]", example_en: "The wolf lives in the forest.", example_uz: "Bo'ri o'rmonda yashaydi.", category: "hayvonlar", emoji: "🐺" },

  // ----------------------- MEVALAR (fruits) -----------------------
  { english: "apple", uzbek: "olma", transcription: "[ˈæp.əl]", example_en: "I eat a red apple.", example_uz: "Men qizil olma yeyman.", category: "mevalar", emoji: "🍎" },
  { english: "banana", uzbek: "banan", transcription: "[bəˈnɑː.nə]", example_en: "The banana is yellow.", example_uz: "Banan sariq.", category: "mevalar", emoji: "🍌" },
  { english: "orange", uzbek: "apelsin", transcription: "[ˈɒr.ɪndʒ]", example_en: "The orange is sweet.", example_uz: "Apelsin shirin.", category: "mevalar", emoji: "🍊" },
  { english: "grape", uzbek: "uzum", transcription: "[ɡreɪp]", example_en: "Grapes grow on a vine.", example_uz: "Uzum tokda o'sadi.", category: "mevalar", emoji: "🍇" },
  { english: "strawberry", uzbek: "qulupnay", transcription: "[ˈstrɔː.bər.i]", example_en: "I love strawberry.", example_uz: "Men qulupnayni yaxshi ko'raman.", category: "mevalar", emoji: "🍓" },
  { english: "watermelon", uzbek: "tarvuz", transcription: "[ˈwɔː.təˌmel.ən]", example_en: "Watermelon is juicy.", example_uz: "Tarvuz sersuv.", category: "mevalar", emoji: "🍉" },
  { english: "lemon", uzbek: "limon", transcription: "[ˈlem.ən]", example_en: "The lemon is sour.", example_uz: "Limon nordon.", category: "mevalar", emoji: "🍋" },
  { english: "peach", uzbek: "shaftoli", transcription: "[piːtʃ]", example_en: "The peach is soft.", example_uz: "Shaftoli yumshoq.", category: "mevalar", emoji: "🍑" },
  { english: "cherry", uzbek: "gilos", transcription: "[ˈtʃer.i]", example_en: "Cherries are small and red.", example_uz: "Gilos kichik va qizil.", category: "mevalar", emoji: "🍒" },
  { english: "pear", uzbek: "nok", transcription: "[peər]", example_en: "The pear is green.", example_uz: "Nok yashil.", category: "mevalar", emoji: "🍐" },
  { english: "pineapple", uzbek: "ananas", transcription: "[ˈpaɪnˌæp.əl]", example_en: "Pineapple is tropical.", example_uz: "Ananas tropik meva.", category: "mevalar", emoji: "🍍" },
  { english: "melon", uzbek: "qovun", transcription: "[ˈmel.ən]", example_en: "The melon smells sweet.", example_uz: "Qovun shirin hidlaydi.", category: "mevalar", emoji: "🍈" },
  { english: "apricot", uzbek: "o'rik", transcription: "[ˈeɪ.prɪ.kɒt]", example_en: "Apricots are orange.", example_uz: "O'rik to'q sariq.", category: "mevalar", emoji: "🍑" },
  { english: "pomegranate", uzbek: "anor", transcription: "[ˈpɒm.ɪˌɡræn.ɪt]", example_en: "The pomegranate has many seeds.", example_uz: "Anorning ko'p donalari bor.", category: "mevalar", emoji: "🔴" },
  { english: "fig", uzbek: "anjir", transcription: "[fɪɡ]", example_en: "The fig is very sweet.", example_uz: "Anjir juda shirin.", category: "mevalar", emoji: "🟣" },

  // ----------------------- RANGLAR (colors) -----------------------
  { english: "red", uzbek: "qizil", transcription: "[red]", example_en: "The apple is red.", example_uz: "Olma qizil.", category: "ranglar", emoji: "🔴" },
  { english: "blue", uzbek: "ko'k", transcription: "[bluː]", example_en: "The sky is blue.", example_uz: "Osmon ko'k.", category: "ranglar", emoji: "🔵" },
  { english: "green", uzbek: "yashil", transcription: "[ɡriːn]", example_en: "The grass is green.", example_uz: "O't yashil.", category: "ranglar", emoji: "🟢" },
  { english: "yellow", uzbek: "sariq", transcription: "[ˈjel.əʊ]", example_en: "The sun is yellow.", example_uz: "Quyosh sariq.", category: "ranglar", emoji: "🟡" },
  { english: "orange", uzbek: "to'q sariq", transcription: "[ˈɒr.ɪndʒ]", example_en: "I have an orange ball.", example_uz: "Menda to'q sariq to'p bor.", category: "ranglar", emoji: "🟠" },
  { english: "purple", uzbek: "binafsha", transcription: "[ˈpɜː.pəl]", example_en: "The flower is purple.", example_uz: "Gul binafsha rangda.", category: "ranglar", emoji: "🟣" },
  { english: "pink", uzbek: "pushti", transcription: "[pɪŋk]", example_en: "She likes pink.", example_uz: "U pushti rangni yoqtiradi.", category: "ranglar", emoji: "🌸" },
  { english: "black", uzbek: "qora", transcription: "[blæk]", example_en: "The cat is black.", example_uz: "Mushuk qora.", category: "ranglar", emoji: "⚫" },
  { english: "white", uzbek: "oq", transcription: "[waɪt]", example_en: "The snow is white.", example_uz: "Qor oq.", category: "ranglar", emoji: "⚪" },
  { english: "brown", uzbek: "jigarrang", transcription: "[braʊn]", example_en: "The bear is brown.", example_uz: "Ayiq jigarrang.", category: "ranglar", emoji: "🟤" },
  { english: "gray", uzbek: "kulrang", transcription: "[ɡreɪ]", example_en: "The elephant is gray.", example_uz: "Fil kulrang.", category: "ranglar", emoji: "🩶" },
  { english: "gold", uzbek: "oltin rang", transcription: "[ɡəʊld]", example_en: "The star is gold.", example_uz: "Yulduz oltin rangda.", category: "ranglar", emoji: "🌟" },

  // ----------------------- MAKTAB (school) -----------------------
  { english: "book", uzbek: "kitob", transcription: "[bʊk]", example_en: "I read a book.", example_uz: "Men kitob o'qiyman.", category: "maktab", emoji: "📖" },
  { english: "pen", uzbek: "ruchka", transcription: "[pen]", example_en: "I write with a pen.", example_uz: "Men ruchka bilan yozaman.", category: "maktab", emoji: "🖊️" },
  { english: "pencil", uzbek: "qalam", transcription: "[ˈpen.səl]", example_en: "The pencil is sharp.", example_uz: "Qalam o'tkir.", category: "maktab", emoji: "✏️" },
  { english: "teacher", uzbek: "o'qituvchi", transcription: "[ˈtiː.tʃər]", example_en: "The teacher is kind.", example_uz: "O'qituvchi mehribon.", category: "maktab", emoji: "👩‍🏫" },
  { english: "student", uzbek: "o'quvchi", transcription: "[ˈstjuː.dənt]", example_en: "The student is smart.", example_uz: "O'quvchi aqlli.", category: "maktab", emoji: "🧑‍🎓" },
  { english: "school", uzbek: "maktab", transcription: "[skuːl]", example_en: "I go to school.", example_uz: "Men maktabga boraman.", category: "maktab", emoji: "🏫" },
  { english: "desk", uzbek: "parta", transcription: "[desk]", example_en: "My books are on the desk.", example_uz: "Kitoblarim partada.", category: "maktab", emoji: "🪑" },
  { english: "bag", uzbek: "sumka", transcription: "[bæɡ]", example_en: "My bag is heavy.", example_uz: "Sumkam og'ir.", category: "maktab", emoji: "🎒" },
  { english: "ruler", uzbek: "chizg'ich", transcription: "[ˈruː.lər]", example_en: "I draw a line with a ruler.", example_uz: "Chizg'ich bilan chiziq chizaman.", category: "maktab", emoji: "📏" },
  { english: "notebook", uzbek: "daftar", transcription: "[ˈnəʊt.bʊk]", example_en: "I write in my notebook.", example_uz: "Men daftarimga yozaman.", category: "maktab", emoji: "📓" },
  { english: "paper", uzbek: "qog'oz", transcription: "[ˈpeɪ.pər]", example_en: "I draw on paper.", example_uz: "Men qog'ozga rasm chizaman.", category: "maktab", emoji: "📄" },
  { english: "eraser", uzbek: "o'chirg'ich", transcription: "[ɪˈreɪ.zər]", example_en: "I use an eraser.", example_uz: "Men o'chirg'ichdan foydalanaman.", category: "maktab", emoji: "🧼" },
  { english: "board", uzbek: "doska", transcription: "[bɔːd]", example_en: "The teacher writes on the board.", example_uz: "O'qituvchi doskaga yozadi.", category: "maktab", emoji: "📋" },
  { english: "lesson", uzbek: "dars", transcription: "[ˈles.ən]", example_en: "The lesson is interesting.", example_uz: "Dars qiziqarli.", category: "maktab", emoji: "📚" },
  { english: "homework", uzbek: "uy vazifasi", transcription: "[ˈhəʊm.wɜːk]", example_en: "I do my homework.", example_uz: "Men uy vazifamni bajaraman.", category: "maktab", emoji: "📝" },

  // ----------------------- OILA (family) -----------------------
  { english: "mother", uzbek: "ona", transcription: "[ˈmʌð.ər]", example_en: "I love my mother.", example_uz: "Men onamni yaxshi ko'raman.", category: "oila", emoji: "👩" },
  { english: "father", uzbek: "ota", transcription: "[ˈfɑː.ðər]", example_en: "My father is tall.", example_uz: "Otam baland bo'yli.", category: "oila", emoji: "👨" },
  { english: "brother", uzbek: "aka / uka", transcription: "[ˈbrʌð.ər]", example_en: "My brother is funny.", example_uz: "Akam kulgili.", category: "oila", emoji: "👦" },
  { english: "sister", uzbek: "opa / singil", transcription: "[ˈsɪs.tər]", example_en: "My sister is little.", example_uz: "Singlim kichkina.", category: "oila", emoji: "👧" },
  { english: "grandmother", uzbek: "buvi", transcription: "[ˈɡrænˌmʌð.ər]", example_en: "My grandmother tells stories.", example_uz: "Buvim ertak aytadi.", category: "oila", emoji: "👵" },
  { english: "grandfather", uzbek: "bobo", transcription: "[ˈɡrænˌfɑː.ðər]", example_en: "My grandfather is wise.", example_uz: "Bobom dono.", category: "oila", emoji: "👴" },
  { english: "baby", uzbek: "chaqaloq", transcription: "[ˈbeɪ.bi]", example_en: "The baby is sleeping.", example_uz: "Chaqaloq uxlayapti.", category: "oila", emoji: "👶" },
  { english: "family", uzbek: "oila", transcription: "[ˈfæm.əl.i]", example_en: "I love my family.", example_uz: "Men oilamni yaxshi ko'raman.", category: "oila", emoji: "👨‍👩‍👧‍👦" },
  { english: "son", uzbek: "o'g'il", transcription: "[sʌn]", example_en: "He is my son.", example_uz: "U mening o'g'lim.", category: "oila", emoji: "👦" },
  { english: "daughter", uzbek: "qiz", transcription: "[ˈdɔː.tər]", example_en: "She is my daughter.", example_uz: "U mening qizim.", category: "oila", emoji: "👧" },
  { english: "uncle", uzbek: "amaki / tog'a", transcription: "[ˈʌŋ.kəl]", example_en: "My uncle is funny.", example_uz: "Amakim kulgili.", category: "oila", emoji: "🧔" },
  { english: "aunt", uzbek: "amma / xola", transcription: "[ɑːnt]", example_en: "My aunt is kind.", example_uz: "Xolam mehribon.", category: "oila", emoji: "👩" },

  // ----------------------- RAQAMLAR (numbers) -----------------------
  { english: "one", uzbek: "bir", transcription: "[wʌn]", example_en: "I have one apple.", example_uz: "Menda bitta olma bor.", category: "raqamlar", emoji: "1️⃣" },
  { english: "two", uzbek: "ikki", transcription: "[tuː]", example_en: "I see two cats.", example_uz: "Men ikkita mushuk ko'raman.", category: "raqamlar", emoji: "2️⃣" },
  { english: "three", uzbek: "uch", transcription: "[θriː]", example_en: "There are three birds.", example_uz: "Uchta qush bor.", category: "raqamlar", emoji: "3️⃣" },
  { english: "four", uzbek: "to'rt", transcription: "[fɔː]", example_en: "A dog has four legs.", example_uz: "Itning to'rtta oyog'i bor.", category: "raqamlar", emoji: "4️⃣" },
  { english: "five", uzbek: "besh", transcription: "[faɪv]", example_en: "I have five fingers.", example_uz: "Mening beshta barmog'im bor.", category: "raqamlar", emoji: "5️⃣" },
  { english: "six", uzbek: "olti", transcription: "[sɪks]", example_en: "Six eggs are in the box.", example_uz: "Qutida oltita tuxum bor.", category: "raqamlar", emoji: "6️⃣" },
  { english: "seven", uzbek: "yetti", transcription: "[ˈsev.ən]", example_en: "A week has seven days.", example_uz: "Haftada yetti kun bor.", category: "raqamlar", emoji: "7️⃣" },
  { english: "eight", uzbek: "sakkiz", transcription: "[eɪt]", example_en: "A spider has eight legs.", example_uz: "O'rgimchakning sakkizta oyog'i bor.", category: "raqamlar", emoji: "8️⃣" },
  { english: "nine", uzbek: "to'qqiz", transcription: "[naɪn]", example_en: "I am nine years old.", example_uz: "Men to'qqiz yoshdaman.", category: "raqamlar", emoji: "9️⃣" },
  { english: "ten", uzbek: "o'n", transcription: "[ten]", example_en: "I can count to ten.", example_uz: "Men o'ngacha sanay olaman.", category: "raqamlar", emoji: "🔟" },
  { english: "zero", uzbek: "nol", transcription: "[ˈzɪə.rəʊ]", example_en: "Zero comes before one.", example_uz: "Nol birdan oldin keladi.", category: "raqamlar", emoji: "0️⃣" },
  { english: "hundred", uzbek: "yuz", transcription: "[ˈhʌn.drəd]", example_en: "One hundred is a big number.", example_uz: "Yuz — katta son.", category: "raqamlar", emoji: "💯" },

  // ----------------------- UMUMIY (general) -----------------------
  { english: "sun", uzbek: "quyosh", transcription: "[sʌn]", example_en: "The sun is bright.", example_uz: "Quyosh yorqin.", category: "umumiy", emoji: "☀️" },
  { english: "moon", uzbek: "oy", transcription: "[muːn]", example_en: "The moon is in the sky.", example_uz: "Oy osmonda.", category: "umumiy", emoji: "🌙" },
  { english: "star", uzbek: "yulduz", transcription: "[stɑː]", example_en: "I see a star.", example_uz: "Men yulduz ko'raman.", category: "umumiy", emoji: "⭐" },
  { english: "water", uzbek: "suv", transcription: "[ˈwɔː.tər]", example_en: "I drink water.", example_uz: "Men suv ichaman.", category: "umumiy", emoji: "💧" },
  { english: "tree", uzbek: "daraxt", transcription: "[triː]", example_en: "The tree is tall.", example_uz: "Daraxt baland.", category: "umumiy", emoji: "🌳" },
  { english: "flower", uzbek: "gul", transcription: "[ˈflaʊ.ər]", example_en: "The flower smells nice.", example_uz: "Gul yoqimli hidlaydi.", category: "umumiy", emoji: "🌷" },
  { english: "house", uzbek: "uy", transcription: "[haʊs]", example_en: "My house is warm.", example_uz: "Mening uyim issiq.", category: "umumiy", emoji: "🏠" },
  { english: "car", uzbek: "mashina", transcription: "[kɑː]", example_en: "The car is fast.", example_uz: "Mashina tez.", category: "umumiy", emoji: "🚗" },
  { english: "ball", uzbek: "to'p", transcription: "[bɔːl]", example_en: "I play with a ball.", example_uz: "Men to'p bilan o'ynayman.", category: "umumiy", emoji: "⚽" },
  { english: "bread", uzbek: "non", transcription: "[bred]", example_en: "I eat bread.", example_uz: "Men non yeyman.", category: "umumiy", emoji: "🍞" },
  { english: "milk", uzbek: "sut", transcription: "[mɪlk]", example_en: "I drink milk.", example_uz: "Men sut ichaman.", category: "umumiy", emoji: "🥛" },
  { english: "egg", uzbek: "tuxum", transcription: "[eɡ]", example_en: "The egg is white.", example_uz: "Tuxum oq.", category: "umumiy", emoji: "🥚" },
  { english: "happy", uzbek: "xursand", transcription: "[ˈhæp.i]", example_en: "I am happy today.", example_uz: "Men bugun xursandman.", category: "umumiy", emoji: "😄" },
  { english: "sad", uzbek: "xafa", transcription: "[sæd]", example_en: "Do not be sad.", example_uz: "Xafa bo'lma.", category: "umumiy", emoji: "😢" },
  { english: "big", uzbek: "katta", transcription: "[bɪɡ]", example_en: "The elephant is big.", example_uz: "Fil katta.", category: "umumiy", emoji: "🐘" },
  { english: "small", uzbek: "kichik", transcription: "[smɔːl]", example_en: "The ant is small.", example_uz: "Chumoli kichik.", category: "umumiy", emoji: "🐜" },
  { english: "hot", uzbek: "issiq", transcription: "[hɒt]", example_en: "The tea is hot.", example_uz: "Choy issiq.", category: "umumiy", emoji: "🔥" },
  { english: "cold", uzbek: "sovuq", transcription: "[kəʊld]", example_en: "The ice is cold.", example_uz: "Muz sovuq.", category: "umumiy", emoji: "❄️" },
  { english: "hello", uzbek: "salom", transcription: "[heˈləʊ]", example_en: "Hello, my friend!", example_uz: "Salom, do'stim!", category: "umumiy", emoji: "👋" },
  { english: "thank you", uzbek: "rahmat", transcription: "[θæŋk juː]", example_en: "Thank you very much.", example_uz: "Katta rahmat.", category: "umumiy", emoji: "🙏" },
];
